Repository typst/typst, pull requests merged in 2025-04, with the labels that each got.

#5420 Switch PDF backend to `krilla`
  Cargo.lock
  Cargo.toml
  crates/typst-cli/src/args.rs
  crates/typst-cli/src/compile.rs
  crates/typst-layout/src/inline/shaping.rs
  crates/typst-library/src/layout/transform.rs
  crates/typst-library/src/visualize/image/raster.rs
  crates/typst-pdf/Cargo.toml
  crates/typst-pdf/src/catalog.rs
  crates/typst-pdf/src/color.rs
  crates/typst-pdf/src/color_font.rs
  crates/typst-pdf/src/content.rs
  crates/typst-pdf/src/convert.rs
  crates/typst-pdf/src/embed.rs
  crates/typst-pdf/src/extg.rs
  crates/typst-pdf/src/font.rs
  crates/typst-pdf/src/gradient.rs
  crates/typst-pdf/src/image.rs
  crates/typst-pdf/src/lib.rs
  crates/typst-pdf/src/link.rs
  crates/typst-pdf/src/metadata.rs
  crates/typst-pdf/src/named_destination.rs
  crates/typst-pdf/src/outline.rs
  crates/typst-pdf/src/page.rs
  crates/typst-pdf/src/paint.rs
  crates/typst-pdf/src/resources.rs
  crates/typst-pdf/src/shape.rs
  crates/typst-pdf/src/text.rs
  crates/typst-pdf/src/tiling.rs
  crates/typst-pdf/src/util.rs
Labels: pdf

#5996 Parse multi-character numbers consistently in math
  crates/typst-syntax/src/parser.rs
  tests/ref/issue-4828-math-number-multi-char.png
  tests/ref/math-frac-precedence.png
  tests/suite/math/frac.typ
  tests/suite/math/syntax.typ
Labels: math, syntax, fix

#5627 Support comparison functions in `array.sorted`
  Cargo.lock
  Cargo.toml
  crates/typst-library/Cargo.toml
  crates/typst-library/src/foundations/array.rs
  tests/suite/foundations/array.typ
Labels: scripting, interface

#6049 Disallow empty font lists
  crates/typst-library/src/text/mod.rs
  tests/suite/text/font.typ
Labels: diagnostics, interface

#5750 Improved ratio and relative length docs
  crates/typst-library/src/layout/ratio.rs
  crates/typst-library/src/layout/rel.rs
Labels: docs

#6027 Document exceptions and alternatives to using `type`
  crates/typst-library/src/foundations/ty.rs
Labels: docs

#6134 Add HTML meta tags for document authors and keywords
  crates/typst-html/src/lib.rs
Labels: html
